apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-monitoring-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gabrielrosinski/devops-practice
    targetRevision: HEAD
    path: "assignment solutions/Monitoring assignment 9/k8s"
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true