apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine-slim
        volumeMounts:
        - name: nginx-conf-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        envFrom:
        - configMapRef:
            name: nginx-config
      volumes:
      - name: nginx-conf-volume
        configMap:
          name: nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf
