# Create custom namespace
apiVersion: v1
kind: Namespace
metadata:
  name: custom-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blaq-dep
  namespace: custom-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blaq
  template:
    metadata:
      labels:
        app: blaq
    spec:
      containers:
        - name: blaq-image
          image: blaq-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081