apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-mon-demo
  namespace: app
  labels:
    app: kube-mon-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-mon-demo
  template:
    metadata:
      labels:
        app: kube-mon-demo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: /metrics
    spec:
      containers:
        - name: app
          image: your-dockerhub/kube-mon-demo:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: READY_DELAY_SECONDS
              value: "5"
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
