apiVersion: v1
kind: Service
metadata:
  name: kube-mon-demo
  namespace: app
  labels:
    app: kube-mon-demo
spec:
  selector:
    app: kube-mon-demo
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
