# Create custom namespace
apiVersion: v1
kind: Namespace
metadata:
  name: blaq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-deployment
  namespace: blaq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fullstack
  template:
    metadata:
      labels:
        app: fullstack
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8088
        - name: httpbin
          image: mccutchen/go-httpbin:v2.2.0
          ports:
            - containerPort: 8080
